### ISSUE TITLE
CT when the sim is finished starting up all non-dynamic schema entries must be registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/atomic-interactions#86]
```
atomic-interactions : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/atomic-interactions/atomic-interactions_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/10/2020, 4:10:34 AM
atomic-interactions : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/atomic-interactions/atomic-interactions_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/10/2020, 4:10:34 AM
atomic-interactions : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io-wrappers/mirror-inputs/?sim=atomic-interactions&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/10/2020, 4:10:34 AM
atomic-interactions : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io-wrappers/state/?sim=atomic-interactions&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/10/2020, 4:10:34 AM
atomic-interactions : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/studio/?sim=atomic-interactions&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
atomicInteractions.atomicInteractionsScreen.model.motionPausedProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586513434286/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/10/2020, 4:10:34 AM
```

**Comment by jbphet** [comment]
Fixed, closing.
